name: Streamlit with Spark

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download and install Apache Spark
        run: |
          wget https://downloads.apache.org/spark/spark-3.2.0/spark-3.2.0-bin-hadoop3.2.tgz
          tar xvf spark-3.2.0-bin-hadoop3.2.tgz
          sudo mv spark-3.2.0-bin-hadoop3.2 /opt/spark

      - name: Set up Spark environment variables
        run: |
          echo "export SPARK_HOME=/opt/spark" >> $GITHUB_ENV
          echo "export PATH=$PATH:/opt/spark/bin:/opt/spark/sbin" >> $GITHUB_ENV

      - name: Run Streamlit app
        run: |
          streamlit run app.py
